# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.v2.jsonschema.json
# golangci-lint configuration
version: "2"

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - misspell
    - unconvert
    - gocritic
    - gocognit
    - gocyclo
    - dupl
    - gosec
    - exhaustive
    - prealloc
    - nilerr
    - nolintlint
    - revive

linters-settings:
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  dupl:
    threshold: 100

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 10

run:
  timeout: 5m
  tests: true